services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: tgtime-auth-app
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${PROMETHEUS_APP_PORT}:${PROMETHEUS_APP_PORT}"
    networks:
      - tgtime-auth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT}/service/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1s
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres:16.2
    container_name: tgtime-auth-db
    restart: always
    ports:
      - "${DATABASE_PG_PORT}:${DATABASE_PG_PORT}"
    volumes:
      - tgtime-auth-data:/var/lib/postgresql/data
      - ./docker/db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DATABASE_PG_NAME}
      POSTGRES_USER: ${DATABASE_PG_USER}
      POSTGRES_PASSWORD: ${DATABASE_PG_PASSWORD}
    networks:
      tgtime-auth-network:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s

  migrate:
    image: migrate/migrate
    networks:
      - tgtime-auth-network
    volumes:
      - ${DATABASE_MIGRATION_DIR}:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${DATABASE_PG_USER}:${DATABASE_PG_PASSWORD}@database:${DATABASE_PG_PORT}/${DATABASE_PG_NAME}?sslmode=${DATABASE_PG_SSL_MODE}", "up"]
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    depends_on:
      app:
        condition: service_healthy
    networks:
      - tgtime-auth-network

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tgtime-auth-network

  postgresql-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: unless-stopped
    networks:
      - tgtime-auth-network
    environment:
      DATA_SOURCE_NAME: "postgres://${DATABASE_PG_USER}:${DATABASE_PG_PASSWORD}@database:${DATABASE_PG_PORT}/${DATABASE_PG_NAME}?sslmode=${DATABASE_PG_SSL_MODE}"
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: true

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "${JAEGER_CLIENT_PORT}:${JAEGER_CLIENT_PORT}/udp" # jaeger-client
      - "6832:6832/udp"
      - "5778:5778"
      - "${JAEGER_PORT_WEB}:${JAEGER_PORT_WEB}" # web
      - "14268:14268"
      - "9411:9411"
    networks:
      - tgtime-auth-network

networks:
  tgtime-auth-network:
    driver: bridge

volumes:
  tgtime-auth-data:
  prometheus_data:
  grafana_data: