global:
  scrape_interval:     2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [":9090"] # TODO: From env?

  - job_name: "app"
    static_configs:
      - targets: ["app:2112"] # TODO: From env?

  - job_name: "postgres"
    static_configs:
      - targets: ["postgresql_exporter:9187"] # TODO: From env?